package net.tc.sakila;
// Generated 24-Apr-2019 8:11:38 PM by Hibernate Tools 5.4.2.Final

/**
 * CustomerList generated by hbm2java
 */
public class CustomerList implements java.io.Serializable {

	private CustomerListId id;

	public CustomerList() {
	}

	public CustomerList(CustomerListId id) {
		this.id = id;
	}

	public CustomerListId getId() {
		return this.id;
	}

	public void setId(CustomerListId id) {
		this.id = id;
	}

}
