package net.tc.world;
// Generated 24-Apr-2019 6:29:43 PM by Hibernate Tools 5.4.2.Final

/**
 * CountryLanguage generated by hbm2java
 */
public class CountryLanguage implements java.io.Serializable {

	private CountryLanguageId id;
	private char isOfficial;
	private float percentage;

	public CountryLanguage() {
	}

	public CountryLanguage(CountryLanguageId id, char isOfficial, float percentage) {
		this.id = id;
		this.isOfficial = isOfficial;
		this.percentage = percentage;
	}

	public CountryLanguageId getId() {
		return this.id;
	}

	public void setId(CountryLanguageId id) {
		this.id = id;
	}

	public char getIsOfficial() {
		return this.isOfficial;
	}

	public void setIsOfficial(char isOfficial) {
		this.isOfficial = isOfficial;
	}

	public float getPercentage() {
		return this.percentage;
	}

	public void setPercentage(float percentage) {
		this.percentage = percentage;
	}

}
